
services:
  db:
    container_name: utsav_db
    image: postgres:17
    ports:
      - "5432:5432"
    networks:
      utsav_net:
        ipv4_address: 172.22.0.2
    environment:
      POSTGRES_DB: lmsdb
      POSTGRES_USER: lmsuser
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lmsuser -d lmsdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    

  backend:
    container_name: utsav_backend
    build:
      context: ..
      dockerfile: DevOps/backend.Dockerfile
    working_dir: /API-PROJECT
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    networks:
      utsav_net:
        ipv4_address: 172.22.0.3
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../LMS/.env:/API-PROJECT/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=lmsdb
      - DB_USER=lmsuser
      - DB_PASSWORD=1234
      - DB_HOST=localhost
      - DB_PORT=5432
      - DOCKERIZED=true

  frontend:
    container_name: utsav_frontend
    build:
      context: ..
      dockerfile: DevOps/frontend.Dockerfile
    ports:
      - "3000:80"
    networks:
      utsav_net:
        ipv4_address: 172.22.0.4
    # depends_on:
    #   backend:
    #     condition: service_healthy
    healthcheck:
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    volumes:
      - ../LMS-react/dist:/app/dist

  nginx:
    container_name: utsav_nginx
    image: nginx
    ports:
      - "80:80"
    networks:
      utsav_net:
        ipv4_address: 172.22.0.5
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:

networks:
  utsav_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
